export const questions = {
    "Hello": "ni hao",
    "You": "ni",
    "Good, ok": "hao",
    "May i ask, excuse me": "qingwen",
    "Please, invite": "qing",
    "Ask": "wen",
    "Be called": "jiao",
    "What": "shenme",
    "Name": "mingzi",
    "I, me": "wo",
    "Know, get to know": "renshi",
    "Very": "hen",
    "Glad, happy": "gaoxing",
    "Sorry": "duibuqi",
    "Surname, family name": "xing",
    "Chinese": "Zhongwen",
    "Be": "shi",
    "You (plural)": "nimen",
    "Everybody": "dajia",
    "he/him": "ta",
    "she/her": "ta",
    "Mr": "xiansheng",
    "Mrs": "taitai",
    "Miss": "xiaojie",
    "Ms": "nushi",
    "Schoolmate": "tongxue",
    "Teacher": "laoshi",
    "Good morning": "zaoshang hao",
    "Good evening": "wanshang hao",
    "Long time no see": "hao jiu bu jian",
    "Good morning": "zaoshang hao",
    "Japan": "riben",
    "people": "ren",
    "Not, no": "bu",
    "Where": "nali",
    "Which": "na",
    "China": "Zhongguo",
    "Country": "guo",
    "UK": "Yingguo",
    "live": "zhu",
    "At, in": "zai",
    "London": "Lundun",
    "Beijing": "Beijing",
    "They,them": "tamen",
    "Hollywood": "Haolaiwu",
    "Celebrity": "mingxing",
    "But": "danshi",
    "US": "Meiguo",
    "Canada": "Jianada",
    "South Africa": "Nanfei",
    "New Zealand": "Xinxilan",
    "Australia": "Aodaliya",
    "Sydney": "Xini",
    "Melbourne": "Mo’erban",
    "Korea": "Hanguo",
    "France": "Faguo",
    "Mexico": "Moxige",
    "Kenya": "Kenniya",
    "Thailand": "Taiguo",
    "Egypt": "Aiji",
    "Singapore": "Xinjiapo",
    "Germany": "Deguo",
    "India": "Yindhu",
    "she/her": "ta",
    "he/him": "ta",
    "this": "zhe",
    "And": "he",
    "Also": "ye",
    "Student": "xuesheng",
    "School": "xuexiao",
    "Journalist": "jizhe",
    "Do": "zuo",
    "Work, job": "gongzuo",
    "Doctor": "yisheng",
    "Hospital": "yiyuan",
    "both/all": "dou",
    "Family, home": "jia",
    "Photo": "zhaopian",
    "Teacher": "laoshi",
    "Nurse": "hushi",
    "Tour guide": "daoyou",
    "Lawyer": "lushi",
    "Chef": "chushi",
    "Secretary": "mishu",
    "Engineer": "gongchengshi",
    "waiter/waitress": "fuwuyuan",
    "Mechanic, repairman": "xiuligong",
    "Barber, hairdresser": "lifashi",
    "Father": "baba",
    "Mother": "mama",
    "Elder sister": "jiejie",
    "Younger sister": "meimei",
    "Elder brother": "gege",
    "Younger brother": "didi",
    "Who": "shei",
    "Shanghai": "Shanghai",
    "Now": "xianzai",
    "How old": "duo da",
    "Years(s) old": "sui",
    "Know": "zhidao",
    "Really, so": "zhen",
    "Tall": "gao",
    "Handsome": "shuai",
    "Cool": "ku",
    "Most": "zui",
    "Like": "xihuan",
    "Basketball": "lanqiu",
    "Athlete": "yundongyuan",
    "Full name": "xingming",
    "Age": "nianling",
    "Place of birth": "chushengdi",
    "Nationality": "guoji",
    "Email box/address": "dianzi youxiang",
    "Animal": "dongwu",
    "Panda": "xiongmao",
    "Cute": "ke’ai",
    "Actor,actress": "yanyuan",
    "Old": "lao",
    "Young": "nianqing",
    "Pretty": "piaoliang",
    "Short (height)": "ai",
    "Hair": "toufa",
    "Long": "chang",
    "Short (length)": "duan",
    "(person) height": "gezi",
    "Telephone": "dianhua",
    "Number, code": "haoma",
    "Mobile phone": "shouji",
    "What, how many/much": "duoshao",
    "Park": "gongyuan",
    "Road": "lu",
    "Number, date (spoken)": "hao",
    "New": "xin",
    "Address": "dizhi",
    "University": "daxue",
    "Block of flats, apartment building": "gongyu",
    "Room": "fangjian",
    "May, can": "keyi",
    "Give, to": "gei",
    "Make a phone call": "da dianhua",
    "Sender": "fajianren",
    "Send": "fasong",
    "Receive": "shoudao",
    "Inbox": "shoujianxiang",
    "Message": "duanxin",
    "Exit, go back": "tuichu",
    "Province (South Yorkshire)": "sheng",
    "City (York)": "shi",
    "District (Piccadilly)": "qu",
    "Street (Brinkworth Terrace)": "jie",
    "Month": "yue",
    "Birthday": "shengri",
    "Really": "zhen de",
    "Today": "jintian",
    "How many": "duoshao",
    "Week": "xingqi",
    "We, us": "women",
    "Have a meal": "chifan",
    "Eat": "chi",
    "Go":" qu",
    "Kitchen": "chufang",
    "How about": "zenmeyang",
    "There": "nali",
    "Chinese food": "Zhongcan",
    "Cuisine, meal": "can",
    "Tasty": "haochi",
    "No problem": "mei wenti",
    "Date (written)": "ri",
    "Play (ball game with hands)": "da",
    "With": "gen",
    "Meet up": "jianmian",
    "Read, see": "kan",
    "Book": "shu",
    "To work": "shangban",
    "Study, learn": "xue",
    "Party": "paidui",
    "Year": "nian",
    "Last year": "qunian",
    "This year": "jinnian",
    "Next year": "mingnian",
    "Yesterday": "zuotian",
    "Tomorrow": "mingtian",
    "Last": "shangge",
    "This": "zhege",
    "Next": "xiage",
    "This": "zhege",
    "Weekend": "zhoumo",
    "Have": "you",
    "Time": "shijian",
    "Want": "yao",
    "Plan": "jihua",
    "Not have": "meiyou",
    "Together": "yiqi",
    "Movie, film": "dianying",
    "What time?": "ji dian",
    "O’clock": "dian",
    "Half (an hour)": "ban",
    "Start": "kaishi",
    "Cinema": "dianyingyuan",
    "Entrance, doorway": "menkou",
    "See, meet": "jian",
    "Very, too": "tai",
    "Friend": "pengyou",
    "Tomorrow": "mingtian",
    "Evening": "wanshang",
    "Thing, matter": "shi",
    "Morning  (9am - midday)": "shangwu",
    "Minute": "fen",
    "Quarter": "ke",
    "English": "Yingyu",
    "Noon": "zhongwu",
    "Food, dish": "cai",
    "Afternoon": "xiawu",
    "Jog": "paobu",
    "Write": "xie",
    "Email": "dianzi youjian",
    "Sing a song": "changge",
    "Get to (a place), arrive": "dao",
    "Sports": "yundong",
    "Dinner": "wanfan",
    "Music": "yinyue",
    "Listen": "ting",
    "Concert": "yinyuehui",
    "Birthday card": "shengri ka",
    "Blog": "boke",
    "Swim": "youyong",
    "Buy": "mai",
    "Thing": "dongxi",
    "Television": "dianshi",
    "Competition, match": "bisai",
    "Red": "hongse",
    "Blue": "lanse",
    "Black": "heise",
    "White": "baise",
    "Green": "luse",
    "Yellow": "huangse",
    "Clothes": "yifu",
    "Skirt": "qunzi",
    "Trousers": "kuzi",
    "T-shirt": "tixu",
    "Shoes": "xie",
    "Coat": "dayi",
    "Sweater": "maoyi",
    "Scarf": "weijin",
    "Shorts": "duanku",
    "Jeans": "niuzaiku",
    "Shirt": "chenshan",
    "Hat": "maozi",
    "One-piece dress": "lianyiqun",
    "Shop assistant": "shouhuoyuan",
    "Buy": "mai",
    "(measure word)": "tiao",
    "Come": "lai",
    "This way": "zhebian",
    "Good-looking": "haokan",
    "Try": "shi",
    "Not bad": "bucuo",
    "Money": "qian",
    "Hundred": "bai",
    "Currency unit of China (yuan)": "kuai",
    "Cheap": "pianyi",
    "A little": "yidianr",
    "Price": "jiaqian",
    "Expensive": "gui",
    "Bookshop": "shudian",
    "Clothes market": "fuzhuang shichang",
    "Supermarket": "chaoshi",
    "Shopping centre": "gouwu zhongxin",
    "Far away": "yuan",
    "Famous": "youming",
    "Last": "shangge",
    "Here": "zheli",
    "Pair": "shuang",
    "Item, piece": "jian",
    "Every, each": "mei",
    "A lot of": "hen duo",
    "Thing": "dongxi",
    "Where": "nar",
    "Building, storey": "lou",
    "How": "zenme",
    "Walk, go": "zou",
    "Passerby": "luren",
    "Front": "qianbian",
    "Back, behind": "houbian",
    "Towards": "wang",
    "Away from": "li",
    "North": "beibian",
    "East": "dongbian",
    "South": "nanbian",
    "West": "xibian",
    "Here": "zher",
    "Right, correct": "dui",
    "Vicinity, nearby": "fujin",
    "Minute": "fenzhong",
    "About": "zuoyou",
    "Rent out, lease": "chuzu",
    "Flat, house": "fangzi",
    "Near": "jin",
    "Dormitory": "sushe",
    "Transportation": "jiaotong",
    "Convenient": "fangbian",
    "Contact, connect": "lianxi",
    "Square metre": "pingfangmi",
    "Bank": "yinhang",
    "Post office": "youju",
    "Subway station": "ditiezhan",
    "Restaurant": "fanguan",
    "Toilet, washroom": "xishoujian",
    "Shop": "shangdian",
    "Cafe": "kafeidian",
    "Pharmacy": "yaodian",
    "Police station": "jingchaju",
    "Hotel": "luguan",
    "Gymnasium": "jianshenfang",
    "It": "ta",
    "Colour": "yanse",
    "Need": "xuyao",
    "Some": "yixie",
    "Take (a vehicle)": "zuo",
    "Bus": "gonggong qiche",
    "Or (in a question)": "haishi",
    "Taxi": "chuzuche",
    "Then": "ranhou",
    "Of course": "dangran",
    "Italy": "Yidali",
    "Restaurant": "canting",
    "Travel": "luxing",
    "Summer holiday": "shujia",
    "Holiday": "jiaqi",
    "The first": "di-yi ge",
    "Train": "huoche",
    "Boat": "chuan",
    "Go sightseeing": "youlan",
    "Climb a mountain": "pashan",
    "Take photos": "paizhao",
    "Visit (a place)": "canguan",
    "Scenic site": "jingdian",
    "Ride (bicycle, etc)": "qi",
    "Bicycle": "zixingche",
    "Aeroplane": "feiji",
    "Petrol station": "huochezhan",
    "Car park": "tingchecheng",
    "Airport": "feijicheng",
    "Football": "zuqiu",
    "Next": "xiage",
    "Think, want": "xiang",
    "Match, competition": "bisai",
    "Ball, ball game": "qiu",
    "Team": "dui",
    "England": "Yinggelan",
    "Stadium, sports ground": "tiyuchang",
    "Hope": "xiwang",
    "Wing": "ying",
    "Tennis": "wangqiu",
    "Can, be able to": "hui",
    "Dance": "tiaowu",
    "Indicator of past actions": "guo",
    "Swim": "youyong",
    "Leisure, have leisure": "xiuxian",
    "Questionnaire": "wenjuan",
    "Gender": "xingbie",
    "Male": "nan",
    "Play (with feet), kick": "ti",
    "Table tennis": "pingpangqiu",
    "Surf": "chonglang",
    "Ski": "huaxue",
    "Dive": "qianshui",
    "Bungee jump": "bengji",
    "Others, other": "qita",
    "Hour": "xiaoshi",
    "Time": "shihou",
    "Hockey": "qugunqiu",
    "Baseball": "bangqiu",
    "Volleyball": "paiqiu",
    "Rugby": "ganlanqiu",
    "Plan": "dasum",
    "Or (in a statement)": "huozhe",
    "Go back": "hui",
    "Do not": "bie",
    "Place": "difang",
    "Hong Kong": "Xianggang",
    "Then, so": "name",
    "After": "yihou",
    "This year": "jinnian",
    "Year": "nian",
    "Fun": "haowan",
    "Say": "shuo",
    "Only": "zhi",
    "Think, feel": "juede",
    "From": "cong",
    "Should": "yinggai",
    "Pretty": "piaoliang",
    "City": "chengshi",
    "Thousand": "qian",
    "History": "lishi",
    "Idea": "zhuyi",
    "Work as an intern": "shixi",
    "Do part time work": "dagong",
    "Go camping": "yeying",
    "Volunteer": "zhiyuanzhe"
}